### ISSUE TITLE
SuperDebugger when trying to load GEOS on MEGA65 core 20220613 (build 192)

### ISSUE THREAD

**Issue by MauriceMEGA65** [bluewaysw/geos#1]
On a more recent MEGA65 core, I cannot start GEOS anymore. I get a "SuperDebugger V6.0" screen instead.
Booting from the release core works fine.

**Comment by jeffreyvanderschilden** [comment]
I've been swapping closed roms on a recent core (r3 192 from 15th of June) with each Kernal rom giving different results and I remember having that debugger a week or 2 ago as well on a kernal from that time as well.

Going with the recent stuff, for example with 920371, the one bit shifter purposed to call final, GEOS starts with only a checkered pattern screen, nothing else is shown, or it simply hangs there, I dunno.

With the recent 920373 kernal, GEOS boots up again, but now it fails with certain drive actions using the SD drive, for example when opening the write program and trying to create a file, it always comes up with an error, no matter the file name.

Lots of variables at play I guess. While the kernal rom is still in heavy development and the core changing, I'm not expecting something like GEOS to be stable any time soon. Or am I wrong?

**Comment by MauriceMEGA65** [comment]
One note: using ROM 920371, GEOS works fine on the release core. Same ROM on the newer core gives me the GEOS boot issue.
Jumping to pre-conclusion: issue is in the core, not in the ROM

**Comment by MauriceMEGA65** [comment]
@Falk, in case you are not following the discussions on Discord, please use ROM 920376 (and up) as stable ROM.
https://discord.com/channels/719326990221574164/795760112425369610/992762961242357842

**Comment by MauriceMEGA65** [comment]
Update:
Using Batch2 core (93d55f0), latest ROM 920376, latest Essential files
https://files.mega65.org/html/main.php?id=f98ee771-5aac-42c0-886f-f68e6ff31c1f

Still same issue: booting GEOS65 ends up in a grey screen (no longer the SuperDebugger error).
It hangs after loading the grey desktop. No icons.

Booting the MEGA65 with the batch 1 release core and then booting GEOS65 works fine.

In all scenarios I'm using the same SD card. So regardless if I boot the release core from slot 0 or the new batch 2 core from slot 1, all the same files (GEOS65.D81, ROM, essential files) are being used.

**Comment by MauriceMEGA65** [comment]
Update:
Issue solved after I installed an external RTC (internal RTC was not ticking on my system).
Apparently GEOS cannot handle a system with a failed internal RTC if an external RTC is not connected.

See also: https://discord.com/channels/719326990221574164/807955369224568912/1033501762520371281

**Comment by MauriceMEGA65** [comment]
Need ticking RTC
