### ISSUE TITLE
something you may not be aware of:

### ISSUE THREAD

**Issue by terrantraymond** [bluewaysw/geos#10]
Way back some years ago when Jim Brain was working on the UIEC2SD some people wanted to boot GEOS on the UIEC2SD,
(The FREE unprotected version that Maurice Randall offers)  When they went to boot GEOS almost when the Desktop appears GEOS would lockup.  Jim Brain payed for a bounty, Ingo Korb and Werner Weicht figured thru this and came up with this:
There is a binary file I guess they created: FAKEHD.bin, so in DOS you type in this 1541 Dos command:
OPEN5,8,15,"xr.fakehd.bin,8
print#5,xw":close5
Now you can boot GEOS and it will not lockup and I wonder if that is the issue or if this might help at all.
My only problem I cant run this because youre only supporting PAL video do you plan on supporing NTSC at some point?
Do I need to add extra RAM to my Mega65?
Anyway this came up a long time back and the solution above does work.
Good luck.

**Comment by bluewaysw** [comment]
Ntsc Support is planned and got prio lately.

**Comment by bluewaysw** [comment]
Interesting remark, this relates to wheels64/128 allow access HD mounts of the UICE2SD. While this is wheels specific support for UICE2SD and is unrelated to MEGA65 GEOS I will close this issue for now.
