### ISSUE TITLE
Mouse (both 1351 and Amiga) no longer working in GEOS65

### ISSUE THREAD

**Issue by MauriceMEGA65** [bluewaysw/geos#18]
The current core 0.96 that is under test, seems to break mouse control in GEOS65.
At this point, GEOS cannot be used(!)

Seems core 0.96 is fixing a joystick port mis-wiring of the current cores. But creating an incompatibility by doing so.

https://discord.com/channels/719326990221574164/1196590643007463459/1198583118530097302
https://discord.com/channels/719326990221574164/1195701571955216434/1198684712605057186

**Comment by gardners** [comment]
I would recommend modifying https://github.com/bluewaysw/geos/blob/master/input/mega1351.s so that it reads the $D620 / $D621 direct jot port 1 POT registers, that always point to port 1, unlike the CIA ones.

It's also possible that unmodified it will work in joy port 2. Not currently tested.

**Comment by bluewaysw** [comment]
Working this fix this...

**Comment by bluewaysw** [comment]
Quick fix merged to master.
