### ISSUE TITLE
Internal floppy disk not working (Format and Create New File)

### ISSUE THREAD

**Issue by MauriceMEGA65** [bluewaysw/geos#2]
Internal 3.5" floppy drive does not seem to work under GEOS65.
Floppy is spinning, but no read/write actions are carried out.

*Format floppy in GEOS: GEOS hangs after a few seconds
*Create a new file (starting GeoWrite for instance): GEOS presents error code "I:26"

Notes:
Floppy (DS DD) is OK, works fine under BASIC.
To create a new file, I tried different file names, all result in "error I:26"

![06BFC510-DFB2-4DE7-B075-C610D5F5C3FC](https://user-images.githubusercontent.com/75681098/197388600-a34ebb49-5401-49d5-91c3-13d44d7e664a.jpeg)

**Comment by bluewaysw** [comment]
Done, changes  merged  to Master.
